In [1]:
!export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64

In [2]:
from utils.utils_init_model import text_logit, fine_tuning_model, eval_model, init_model, logit_prob, load_word_index
import time
from nltk.tokenize import word_tokenize
import torch
import torch.nn.functional as F
# import jax.numpy as jnp
from jax import random

import math
# from .attack_helper import get_synonyms, codemix_perturbation, synonym_replacement, swap_minimum_importance_words, trans_dict

import nltk
from nltk.corpus import stopwords
# nltk.download('stopwords')
stop_words_set = []
for w in stopwords.words('indonesian'):
    stop_words_set.append(w)

from icecream import ic


import nltk
from nltk.corpus import wordnet
from nltk.corpus import stopwords

import copy
from deep_translator import GoogleTranslator
import numpy as np
import random
# from utils.utils_semantic_use import USE
from utils.utils_init_dataset import set_seed, load_dataset_loader
from sklearn.metrics import accuracy_score

import torch
device = torch.device("cuda")

import tensorflow as tf
tf.compat.v1.enable_eager_execution()
# tf.enable_eager_execution()
# import tensorflow.compat.v1 as tf
import tensorflow_hub as hub
import os
# os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
# os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"] = "7"
# tf.config.run_functions_eagerly(True)
tf.executing_eagerly()

Instructions for updating:
non-resource variables are not supported in the long term


True

In [3]:
# !pip install jax
# !pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html  # Note: wheels only available on linux.

In [4]:
class USE(object):
    def __init__(self):
        import tensorflow_hub as hub
        super(USE, self).__init__()
        module_url = "https://tfhub.dev/google/universal-sentence-encoder/4" #@param ["https://tfhub.dev/google/universal-sentence-encoder/4", "https://tfhub.dev/google/universal-sentence-encoder-large/5"]
        self.embed = hub.load(module_url)
        # print(tf.executing_eagerly())
        # self.embed = hub.load( DataManager.load("AttackAssist.UniversalSentenceEncoder") )

    def semantic_sim(self, sentA : str, sentB : str) -> float:
        """
        Args:
            sentA: The first sentence.
            sentB: The second sentence.

        Returns:
            Cosine distance between two sentences.
        
        """
        ret = self.embed([sentA, sentB]).numpy()
        return ret[0].dot(ret[1]) / (np.linalg.norm(ret[0]) * np.linalg.norm(ret[1]))

    def after_attack(self, input, adversarial_sample):
        if adversarial_sample is not None:
            return self.calc_score(input["x"], adversarial_sample)
# tf.config.run_functions_eagerly(True)
# USE()

In [5]:
# class USE(object):
#     def __init__(self, module_url=None):
#         super(USE, self).__init__()
#         module_url = "https://tfhub.dev/google/universal-sentence-encoder/4" #@param ["https://tfhub.dev/google/universal-sentence-encoder/4", "https://tfhub.dev/google/universal-sentence-encoder-large/5"]
#         self.embed = hub.load(module_url)
        
#         def embed(input):
#             return model(input)
        
#         # config = tf.compat.v1.ConfigProto()
#         # config.gpu_options.allow_growth = True
#         # self.sess = tf.compat.v1.Session(config=config)
#         # self.sess.run([tf.compat.v1.global_variables_initializer(), tf.compat.v1.tables_initializer()])

#     def semantic_sim(self, sents1, sents2):
#         # with tf.Session() as session:
#         #     session.run([tf.global_variables_initializer(), tf.tables_initializer()])
#         #     with tf.device('GPU'):
#         #         message_embeddings_ = session.run(self.embed([sents1, sents2]))
        
#         if sents1.lower() == sents2.lower():
#             return 1.000
        
#         message_embeddings_ = self.embed([sents1, sents2])
#         # message_embeddings_ = message_embeddings_.eval(session=self.sess)
#         corr = np.tensordot(message_embeddings_, message_embeddings_, axes=(-1,-1))
        
#         if corr[0][1] > 1:
#             return 1.000
#         return corr[0][1]

In [6]:
def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)

def get_synonyms(word):
    if word in stop_words_set:
        return [word]

    word_lemmas = wordnet.lemmas(word, lang="ind")
    
    hypernyms = []
    for lem in word_lemmas:
        hypernyms.append(lem.synset().hypernyms())

    if not any(hypernyms):
        return [word]
    
    lemma_corp = []
    
    for hypernym in hypernyms:
        if(len(hypernym) < 1):
            continue
        else:
            lemma_corp.append(hypernym[0].lemmas(lang="ind"))
            
    lemmas = set()
    for list_lemmas in lemma_corp:
        if(len(list_lemmas) < 1):
            lemmas.add(word)
        else:
            for l in list_lemmas:
                lemmas.add(l.name())
    
    clean_synonyms = set()
    for syn in lemmas.copy():
        synonym = syn.replace("_", " ").replace("-", " ").lower()
        synonym = "".join([char for char in synonym if char in ' qwertyuiopasdfghjklzxcvbnm'])
        clean_synonyms.add(synonym) 
    if word in clean_synonyms:
        clean_synonyms.remove(word)
    
    if len(list(clean_synonyms)) < 1:
        return [word]
    else:
        return list(clean_synonyms)

def codemix_perturbation(words, target_lang, words_perturb):
    """
    'su': 'sundanese'
    'jw': 'javanese'
    'ms': 'malay'
    'en': 'english'
    """
    translator = GoogleTranslator(source="id", target=target_lang)
    
    new_wp = []
    for wp in words_perturb:
        new_wp.append(wp[1])
    
    new_wp_trans = dict(zip(new_wp, translator.translate_batch(new_wp)))
    
    supported_langs = ["su", "jw", "ms", "en", "fr", "it"]
    
    if target_lang not in supported_langs:
        raise ValueError('Language Unavailable')
    
    if len(words_perturb) >= 1:
        for perturb_word in new_wp_trans.keys():
            new_words = [new_wp_trans[perturb_word] if word == perturb_word and word.isalpha() else word for word in words]

    return ' '.join(new_words)

def synonym_replacement(words, words_perturb):    
    # new_words = words.copy()
       
    if len(words_perturb) >= 1:
        for perturb_word in words_perturb:
            new_words = [get_synonyms(word)[0] if word == perturb_word[1] and word.isalpha() else word for word in words]

    sentence = ' '.join(new_words)
    
    return sentence

# fungsi untuk mencari kandidat lain ketika sebuah kandidat perturbasi kurang dari sim_score_threshold
def swap_minimum_importance_words(words_perturb, top_importance_words):
    print("pointer")
    def get_minimums(word_tups):
        arr = []
        for wt in word_tups:
            if wt[2] == min(top_importance_words, key = lambda t: t[2])[2]:
                arr.append(wt)
        return arr
    
    # get list of words with minimum importance score
    minimum_import = get_minimums(top_importance_words)
    unlisted = list(set(words_perturb).symmetric_difference(set(top_importance_words)))
    
    ic(unlisted)
    
    len_wp = len(top_importance_words)
    len_ul = len(unlisted)
    
    res = []
    for i in range(len_wp):
        if top_importance_words[i] in minimum_import:
            temp_wp = list(copy.deepcopy(top_importance_words))
            if len(temp_wp) == 0:
                break
            
            swapped_wp = np.array([(temp_wp) for i in range(len_ul)])
            
            ic(swapped_wp)
            for j in range(len(swapped_wp)):
                temp_sm = np.vstack((swapped_wp[j], tuple(unlisted[j])))
                
                res.append(temp_sm.tolist())
            temp_wp.pop(i)
                
    return res

def trans_dict(wordlist, perturbation_technique, lang=None):
    translated_wordlist = {}
    # ic(wordlist)
    if perturbation_technique == "codemixing":
        translator = GoogleTranslator(source="id", target=lang)
        
        for word in wordlist:
            if word.isalpha():
                translated_wordlist[word] = translator.translate(word)
            else:
                translated_wordlist[word] = word
    else:
        for word in wordlist:
            translated_wordlist[word] = get_synonyms(word)[0]
            
    return translated_wordlist

In [7]:
def attack(text_ls,
           true_label,
           predictor,
           tokenizer,
           att_ratio,
           perturbation_technique,
           lang_codemix=None,
           sim_predictor=None,
           sim_score_threshold=0,
           sim_score_window=15,
           batch_size=32, 
           import_score_threshold=-1.):
    
    start_time = time.time()
    
    label_dict = {
        'positive': 0, 
        'neutral': 1, 
        'negative': 2}
    
    original_text = text_ls
    orig_label, orig_probs, orig_prob = logit_prob(text_ls, predictor, tokenizer)
    
    if len(original_text.split()) < sim_score_window:
        sim_score_threshold = 0.1  
    
#     SEK SALAAHHHHHH
    if true_label != orig_label:
        running_time = round(time.time() - start_time, 2)
        # perturbed_text, perturbed_semantic_sim, orig_label, orig_probs, perturbed_label, perturbed_probs, translated_words, running_time
        orig_probs = np.round(orig_probs.detach().cpu().numpy().tolist(),4)
        return original_text, 1.000, orig_label, orig_probs, orig_label, orig_probs,'', running_time
    else:
        text_ls = original_text.split()
        text_ls = [word for word in text_ls if word.isalnum()]
        len_text = len(text_ls)
        ic(len_text)
        half_sim_score_window = (sim_score_window - 1) // 2
        # num_queries = 1
        
        leave_1_texts = [' '.join(text_ls[:ii] + [tokenizer.mask_token] + text_ls[min(ii + 1, len_text):]) for ii in range(len_text)]
                
        leave_1_probs = []
        leave_1_probs_argmax = []
        # num_queries += len(leave_1_texts)
        
# torch.inference mode
        for text_leave_1 in leave_1_texts:
            orig_label_leave_1, orig_probs_leave_1, orig_prob_leave_1 = logit_prob(text_leave_1, predictor, tokenizer)
            leave_1_probs.append(orig_probs_leave_1.detach().cpu().numpy())
            leave_1_probs_argmax.append(orig_label_leave_1)
        
        running_time_a = round(time.time() - start_time, 2)
        ic(running_time_a)
        
        leave_1_probs = torch.tensor(leave_1_probs).to("cuda:0")
        
        orig_prob_extended=np.empty(len_text)
        orig_prob_extended.fill(orig_prob)
        orig_prob_extended = torch.tensor(orig_prob_extended).to("cuda:0")
        
        arr1 = orig_prob_extended - leave_1_probs[:,orig_label] + float(leave_1_probs_argmax != orig_label)
        arr2 = (leave_1_probs.max(dim=-1)[0].to("cuda:0") - orig_probs[leave_1_probs_argmax].to("cuda:0"))
        
        import_scores = arr1*arr2
        import_scores = [im * -1 for im in import_scores]
        
        words_perturb = []
        for idx, score in sorted(enumerate(import_scores), key=lambda x: x[1], reverse=True):
            try:
                if score > import_score_threshold and text_ls[idx] not in stop_words_set:
                    words_perturb.append((idx, text_ls[idx], score.item()))
            except Exception as e:
                print(e)
                print(idx, len(text_ls), import_scores.shape, text_ls, len(leave_1_texts))
        
        num_perturbation = math.floor(len(words_perturb)*att_ratio)
        
        if num_perturbation < 1:
            num_perturbation = 1
        
#       top words perturb berisi list kata terpenting yang tidak akan diswitch ketika first_codemix_sim_score < sim_score_threshold
        top_words_perturb = words_perturb[:num_perturbation]
        trans_word = [twp[1] for twp in top_words_perturb]

        if perturbation_technique == "codemixing":
            perturbed_text = codemix_perturbation(text_ls, lang_codemix, top_words_perturb)
        elif perturbation_technique == "synonym_replacement":
            perturbed_text = synonym_replacement(text_ls, top_words_perturb)
        
        start_time_use = time.time()
        first_perturbation_sim_score = sim_predictor.semantic_sim(original_text, perturbed_text)
        end_time_use = round(time.time() - start_time, 2)
        
        ic(end_time_use)
        
        ic(first_perturbation_sim_score)
        
        words_perturb_candidates = []
        if first_perturbation_sim_score < sim_score_threshold:
            words_perturb_candidates.append(top_words_perturb)
            swapped = swap_minimum_importance_words(words_perturb, top_words_perturb)
            for s in swapped:
                words_perturb_candidates.append(s)

            words_perturb_candidates = [[tuple(w) for w in wpc] for wpc in words_perturb_candidates]

            candidate_comparison = {}
            for wpc in words_perturb_candidates:
                
                if perturbation_technique == "codemixing":
#                     bisa dicache, gaperlu request satu2
                    perturbed_candidate = codemix_perturbation(text_ls, lang_codemix, wpc)
                elif perturbation_technique == "synonym_replacement":
                    perturbed_candidate = synonym_replacement(text_ls, wpc)
                    
                perturbed_candidate_sim_score = sim_predictor.semantic_sim(original_text, perturbed_candidate)
                
                candidate_comparison[perturbed_candidate] = (perturbed_candidate_sim_score, wpc[-1][-1], wpc)

            sorted_candidate_comparison = sorted(candidate_comparison.keys(), key=lambda x: (float(candidate_comparison[x][0]), float(candidate_comparison[x][1])), reverse=True)

            perturbed_text = sorted_candidate_comparison[0]
            
            top_words_perturb = candidate_comparison[sorted_candidate_comparison[0]][-1]
            trans_word = [twp[1] for twp in top_words_perturb]
            
        perturbed_semantic_sim = sim_predictor.semantic_sim(original_text, perturbed_text)
        if perturbed_semantic_sim < sim_score_threshold:
            perturbed_text = original_text
            perturbed_semantic_sim = 1.000
        
        perturbed_label, perturbed_probs, perturbed_prob = logit_prob(perturbed_text, predictor, tokenizer)
        
        
        translated_words = trans_dict(trans_word, perturbation_technique, lang_codemix)
        
        orig_probs = np.round(orig_probs.detach().cpu().numpy().tolist(),4)
        perturbed_probs = np.round(perturbed_probs.detach().cpu().numpy().tolist(),4)
        
        running_time = round(time.time() - start_time, 2)
        
        
        return perturbed_text, perturbed_semantic_sim, orig_label, orig_probs, perturbed_label, perturbed_probs, translated_words, running_time

In [8]:
model_target="IndoBERT"
downstream_task="sentiment"
attack_strategy="adversarial"
# finetune_epoch=1
num_sample=50
# exp_name=
perturbation_technique="codemixing"
perturb_ratio=0.4
perturb_lang="en"
seed=26092020
dataset="valid"

set_seed(seed)
use = USE()

2022-04-12 10:24:35.049047: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib:/usr/local/cuda/lib
2022-04-12 10:24:35.050411: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [9]:
tokenizer, config, finetuned_model = init_model(model_target, downstream_task, seed)
w2i, i2w = load_word_index(downstream_task)

train_dataset, train_loader, train_path = load_dataset_loader(downstream_task, 'train', tokenizer)
valid_dataset, valid_loader, valid_path = load_dataset_loader(downstream_task, 'valid', tokenizer)
test_dataset, test_loader, test_path = load_dataset_loader(downstream_task, 'test', tokenizer)

finetuned_model.to(device)
# finetuned_model = fine_tuning_model(model, i2w, train_loader, valid_loader, finetune_epoch)

if dataset == "valid":
    exp_dataset = valid_dataset.load_dataset(valid_path)[381:381+num_sample]
elif dataset == "train":
    exp_dataset = train_dataset.load_dataset(train_path)
# exp_dataset = dd.from_pandas(exp_dataset, npartitions=10)
# exp_dataset = te.DataFrame.from_pandas(exp_dataset)
text,label = None,None

In [11]:
if downstream_task == 'sentiment':
    text = 'text'
    label = 'sentiment'
    exp_dataset[['perturbed_text', 'perturbed_semantic_sim', 'pred_label', 'pred_proba', 'perturbed_label', 'perturbed_proba', 'translated_word(s)', 'running_time(s)']] = exp_dataset.progress_apply(
        lambda row: attack(
            text_ls = row.text,
            true_label = row.sentiment,
            predictor = finetuned_model,
            tokenizer = tokenizer, 
            att_ratio = perturb_ratio,
            perturbation_technique = perturbation_technique,
            lang_codemix = perturb_lang,
            sim_predictor = use), axis=1, result_type='expand'
    )
elif downstream_task == 'emotion':
    text = 'tweet'
    label = 'label'
    exp_dataset[['perturbed_text', 'perturbed_semantic_sim', 'pred_label', 'pred_proba', 'perturbed_label', 'perturbed_proba', 'translated_word(s)', 'running_time(s)']] = exp_dataset.progress_apply(
        lambda row: attack(
            text_ls = row.tweet.values,
            true_label = row.label.values,
            predictor = finetuned_model,
            tokenizer = tokenizer, 
            att_ratio = perturb_ratio,
            perturbation_technique = perturbation_technique,
            lang_codemix = perturb_lang,
            sim_predictor = use), axis=1, result_type='expand'
    )

before_attack = accuracy_score(exp_dataset[label], exp_dataset['pred_label'])
after_attack = accuracy_score(exp_dataset[label], exp_dataset['perturbed_label'])

exp_dataset.loc[exp_dataset.index[0], 'before_attack_acc'] = before_attack
exp_dataset.loc[exp_dataset.index[0], 'after_attack_acc'] = after_attack
exp_dataset.loc[exp_dataset.index[0], 'avg_semantic_sim'] = exp_dataset["perturbed_semantic_sim"].mean()
exp_dataset.loc[exp_dataset.index[0], 'avg_running_time(s)'] = exp_dataset["running_time(s)"].mean()

  0%|                                                                        | 0/50 [00:00<?, ?it/s]ic| len_text: 13
ic| running_time_a: 0.46
ic| end_time_use: 1.25
ic| first_perturbation_sim_score: 1.0000001
  4%|██▌                                                             | 2/50 [00:02<00:50,  1.05s/it]ic| len_text: 17
ic| running_time_a: 0.63
ic| end_time_use: 3.1
ic| first_perturbation_sim_score: 0.9733958
  6%|███▊                                                            | 3/50 [00:05<01:43,  2.21s/it]ic| len_text: 12
ic| running_time_a: 0.32
ic| end_time_use: 1.47
ic| first_perturbation_sim_score: 0.89145684
  8%|█████                                                           | 4/50 [00:08<01:46,  2.31s/it]ic| len_text: 26
ic| running_time_a: 0.89
ic| end_time_use: 2.22
ic| first_perturbation_sim_score: 0.92155635
 10%|██████▍                                                         | 5/50 [00:12<02:11,  2.93s/it]ic| len_text: 22
ic| running_time_a: 0.9
ic| end_time_use: 3.89

NotValidPayload: 3 --> text must be a valid text with maximum 5000 character, otherwise it cannot be translated

### Fungsi Awal banget

In [17]:
attack(
    text_ls = exp_dataset.iloc[[48]].text.item(),
    true_label = 0,
    predictor = finetuned_model,
    tokenizer = tokenizer, 
    att_ratio = perturb_ratio,
    perturbation_technique = perturbation_technique,
    lang_codemix = perturb_lang,
    sim_predictor = use
)

ic| len_text: 60
ic| running_time_a: 2.01


[(59, 'diragukan', 0.001480978060399707), (27, 'enak', 0.0006103660272316347), (18, 'burgundy', 0.0005351185233486433), (55, 'makanan', 0.000532135112141674), (12, 'dago', 0.0004499789485095107), (8, 'romantis', 0.0003965279976370084), (46, 'taman', 0.00039581217539819136), (40, 'rerumputan', 0.00039318750260974866), (7, 'malam', 0.000384060906586825)]


ic| end_time_use: 13.71
ic| first_perturbation_sim_score: 0.96317273


('buat kalian yang cuma tahu tempat makan night romantic yang ada di dago boleh dicoba deh makan di burgundy sini di sini sih menurut saya tempat yang nice banget buat ngadem selain tempat nya yang hening kita juga bisa melihat grass yang hijau meski cuma di garden nya hehehe tapi balik lagi buat saya sih food haha tidak usah doubtful',
 0.96317273,
 0,
 array([9.981e-01, 8.000e-04, 1.100e-03]),
 0,
 array([0.9943, 0.0013, 0.0044]),
 {'diragukan': 'doubtful',
  'enak': 'nice',
  'burgundy': 'burgundy',
  'makanan': 'food',
  'dago': 'dago',
  'romantis': 'romantic',
  'taman': 'garden',
  'rerumputan': 'grass',
  'malam': 'night'},
 17.46)

### Coba optimize di USE nya

In [12]:
attack(
    text_ls = exp_dataset.iloc[[48]].text.item(),
    true_label = 0,
    predictor = finetuned_model,
    tokenizer = tokenizer, 
    att_ratio = perturb_ratio,
    perturbation_technique = perturbation_technique,
    lang_codemix = perturb_lang,
    sim_predictor = use
)

ic| len_text: 60
ic| running_time_a: 2.94
/tmp/ipykernel_3216979/2609633789.py:56: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  leave_1_probs = torch.tensor(leave_1_probs).to("cuda:0")


[(59, 'diragukan', 0.001480978060399707), (27, 'enak', 0.0006103660272316347), (18, 'burgundy', 0.0005351185233486433), (55, 'makanan', 0.000532135112141674), (12, 'dago', 0.0004499789485095107), (8, 'romantis', 0.0003965279976370084), (46, 'taman', 0.00039581217539819136), (40, 'rerumputan', 0.00039318750260974866), (7, 'malam', 0.000384060906586825)]


ic| end_time_use: 7.37
ic| first_perturbation_sim_score: 0.9631725


('buat kalian yang cuma tahu tempat makan night romantic yang ada di dago boleh dicoba deh makan di burgundy sini di sini sih menurut saya tempat yang nice banget buat ngadem selain tempat nya yang hening kita juga bisa melihat grass yang hijau meski cuma di garden nya hehehe tapi balik lagi buat saya sih food haha tidak usah doubtful',
 0.9631725,
 0,
 array([9.981e-01, 8.000e-04, 1.100e-03]),
 0,
 array([0.9943, 0.0013, 0.0044]),
 {'diragukan': 'doubtful',
  'enak': 'nice',
  'burgundy': 'burgundy',
  'makanan': 'food',
  'dago': 'dago',
  'romantis': 'romantic',
  'taman': 'garden',
  'rerumputan': 'grass',
  'malam': 'night'},
 10.45)

### Coba Optimize step 2+codemix perturbation pake batch

In [10]:
attack(
    text_ls = exp_dataset.iloc[[48]].text.item(),
    true_label = 0,
    predictor = finetuned_model,
    tokenizer = tokenizer, 
    att_ratio = perturb_ratio,
    perturbation_technique = perturbation_technique,
    lang_codemix = perturb_lang,
    sim_predictor = use
)

ic| len_text: 60
ic| running_time_a: 3.38
/tmp/ipykernel_3411520/2609633789.py:56: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  leave_1_probs = torch.tensor(leave_1_probs).to("cuda:0")
ic| end_time_use: 6.72
ic| first_perturbation_sim_score: 0.9972706


('buat kalian yang cuma tahu tempat makan night romantis yang ada di dago boleh dicoba deh makan di burgundy sini di sini sih menurut saya tempat yang enak banget buat ngadem selain tempat nya yang hening kita juga bisa melihat rerumputan yang hijau meski cuma di taman nya hehehe tapi balik lagi buat saya sih makanan haha tidak usah diragukan',
 0.9972706,
 0,
 array([9.981e-01, 8.000e-04, 1.100e-03]),
 0,
 array([9.977e-01, 9.000e-04, 1.400e-03]),
 {'diragukan': 'doubtful',
  'enak': 'nice',
  'burgundy': 'burgundy',
  'makanan': 'food',
  'dago': 'dago',
  'romantis': 'romantic',
  'taman': 'garden',
  'rerumputan': 'grass',
  'malam': 'night'},
 10.72)

In [29]:
word = 'buat kalian yang cuma tahu tempat makan malam romantis yang ada di dago , boleh dicoba deh makan di burgundy sini , di sini sih menurut saya tempat yang enak banget buat ngadem selain tempat nya yang hening kita juga bisa melihat rerumputan yang hijau meski cuma di taman nya , hehehe . tapi balik lagi buat saya sih makanan , haha . tidak usah diragukan .'
words = word.split()
wp = [(59, 'diragukan', 0.001480978060399707), (27, 'enak', 0.0006103660272316347), (18, 'burgundy', 0.0005351185233486433), (55, 'makanan', 0.000532135112141674), (12, 'dago', 0.0004499789485095107), (8, 'romantis', 0.0003965279976370084), (46, 'taman', 0.00039581217539819136), (40, 'rerumputan', 0.00039318750260974866), (7, 'malam', 0.000384060906586825)]
target_lang = "en"

start_time = time.time()
codemix_perturbation(words, target_lang, wp)
print(round(time.time() - start_time, 2))

2.37


In [21]:
exp_dataset.iloc[[48]].text.item()

'buat kalian yang cuma tahu tempat makan malam romantis yang ada di dago , boleh dicoba deh makan di burgundy sini , di sini sih menurut saya tempat yang enak banget buat ngadem selain tempat nya yang hening kita juga bisa melihat rerumputan yang hijau meski cuma di taman nya , hehehe . tapi balik lagi buat saya sih makanan , haha . tidak usah diragukan .'

In [2]:

import tensorflow as tf

physical_devices = tf.config.experimental.list_physical_devices('GPU')
print(physical_devices)
if physical_devices:
    tf.config.experimental.set_memory_growth(physical_devices[0], True)

[]


2022-04-12 08:25:36.804004: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib:/usr/local/cuda/lib
2022-04-12 08:25:36.805836: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [3]:
physical_devices = tf.config.list_physical_devices('GPU')
print("Num GPUs:", len(physical_devices))
# !pip list cudnn

Num GPUs: 0


In [34]:
texts = ['diragukan', 'enak', 'burgundy', 'makanan', 'dago', 'romantis', 'taman', 'rerumputan', 'malam']

start_time = time.time()
translated_1 = []
translator = GoogleTranslator(source="id", target="en")
for txt in texts:
    translated_1.append(translator.translate(txt))
print(round(time.time() - start_time, 2))

3.77


In [35]:
start_time = time.time()
translated_2 = translator.translate_batch(texts)
print(round(time.time() - start_time, 2))

2.44


In [ ]:
# !. myenv/bin/activate
# !pip uninstall tensorflow -y
# !pip uninstall tensorflow-gpu -y

!pip install tensorflow --ignore-installed

In [4]:
# %export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
!echo $LD_LIBRARY_PATH

/usr/local/cuda/lib:/usr/local/cuda/lib
